-- 卡信息表
CREATE TABLE IF NOT EXISTS card (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cardnumber VARCHAR(50) NOT NULL UNIQUE,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  balance DECIMAL(10,2) DEFAULT 0.00,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 登录日志表
CREATE TABLE IF NOT EXISTS login_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cardnumber VARCHAR(50) NOT NULL,
  login_time DATETIME,
  logout_time DATETIME,
  duration INT,
  fee DECIMAL(10,2) DEFAULT 0.00
);

-- 充值日志表
CREATE TABLE IF NOT EXISTS recharge_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cardnumber VARCHAR(32) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  time DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 退费日志表
CREATE TABLE IF NOT EXISTS refund_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cardnumber VARCHAR(32) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  time DATETIME DEFAULT CURRENT_TIMESTAMP
);